### ISSUE TITLE
interactive_evaluation.ipynb issue

### ISSUE THREAD

**Issue by munirjojoverge** [MaximeBouton/AutomotiveSafeRL#3]
While running the first cell:
"using Revise
includet("../evaluation/helpers.jl")
includet("../src/render_helpers.jl")
"
and after going through some package installation issues i got the following error:

┌ Info: Precompiling POMDPModelChecking [abefb91b-a28c-5ab9-9bd9-026e532d7b0e]
└ @ Base loading.jl:1192
┌ Error: evaluation error
│   mod = Main
│   ex = mutable struct InterpolationOverlay{M} <: (SceneOverlay where M <: Union{CarMDP, PedMDP, PedCarMDP})
    #= /home/munir/Documents/workspace/AutomotiveSafeRL-master/src/render_helpers.jl:227 =#
    verbosity::Int
    #= /home/munir/Documents/workspace/AutomotiveSafeRL-master/src/render_helpers.jl:228 =#
    color::Colorant
    #= /home/munir/Documents/workspace/AutomotiveSafeRL-master/src/render_helpers.jl:229 =#
    font_size::Int
    #= /home/munir/Documents/workspace/AutomotiveSafeRL-master/src/render_helpers.jl:230 =#
    id::Int
    #= /home/munir/Documents/workspace/AutomotiveSafeRL-master/src/render_helpers.jl:231 =#
    mdp::M
    #= /home/munir/Documents/workspace/AutomotiveSafeRL-master/src/render_helpers.jl:232 =#
    models::Dict{Int64, DriverModel}
    #= /home/munir/Documents/workspace/AutomotiveSafeRL-master/src/render_helpers.jl:233 =#
    ped_id::Int64
    #= /home/munir/Documents/workspace/AutomotiveSafeRL-master/src/render_helpers.jl:234 =#
    car_id::Int64
    #= /home/munir/Documents/workspace/AutomotiveSafeRL-master/src/render_helpers.jl:235 =#
    obs::Scene
end

**Comment by MaximeBouton** [comment]
I am not sure what causes this error, which version of julia are you running? 
Did you restart the kernel after installing the packages?
you could also try without Revise.

**Comment by munirjojoverge** [comment]
Julia Version 1.0.4 (2019-05-16)
Ubuntu 18.04

**Comment by MaximeBouton** [comment]
I ran it locally and Revise seemed to cause the issue, I am not sure why. In the mean time I removed it from the notebook. 

This gave me the opportunity for a few maintenance operation on several repo, I suggest to pull the master of `AutomotivePOMDPs` and `PedCar` to reflect those fixes.

**Comment by munirjojoverge** [comment]
I believe we are moving forward.. The include run with no problem.
Unfortunately, while running cell 3:
pomdp, policy, updater, initialscene_scenario = load_policies_and_environment("RL", "tracker", "3");
I got this error: 
SystemError: opening file ../RNNFiltering/model_car_1.bson: No such file or directory

While inspecting this function, I see that here's where you load the .bson but nowhere else is generated.
car_models[i] = BSON.load("../RNNFiltering/model_car_$i.bson")[:model]

So I'm assuming this file just needs to be pushed on the repo?

**Comment by MaximeBouton** [comment]
Yes those are the trained models, I usually don't upload binaries to github, some of the models are large. 
I have some saved locally, please contact us via email.

If you want to reproduce our results, I suggest re-training the models, it should not take more than a 
couple hours on CPU. 

Here are the scripts, for more details consult our paper: https://arxiv.org/abs/1904.11483

RNN ensemble: https://github.com/MaximeBouton/AutomotiveSafeRL/blob/master/RNNFiltering/bagging_training.jl
(it trains one RNN filter, to train an ensemble just run it several times with different seeds, it generates a new data set every time)

This script is used to train the RL policies, the non mask version should be straightforward to train:
https://github.com/MaximeBouton/AutomotiveSafeRL/blob/master/training_scripts/pedcar_dqn.jl

Computing the value Iteration mask requires much more computation ressources: 
https://github.com/MaximeBouton/AutomotiveSafeRL/blob/master/training_scripts/pedcar_vi.jl

**Comment by munirjojoverge** [comment]
Thanks a lot Maxime!
I will train locally to check results.
btw..one quick suggestion for the evaluation_scenarios notebook: add "film =" in front of "animate_history", that way the video pops out on the same notebook and the results are ready to be checked visually. it's very convenient.
