### ISSUE TITLE
ERROR : add https://github.com/MaximeBouton/AutomotiveSafeRL but exist  file.Delete the file not work!

### ISSUE THREAD

**Issue by tingtingLiuLiu** [MaximeBouton/AutomotiveSafeRL#6]
(@v1.6) pkg> add https://github.com/MaximeBouton/AutomotiveSafeRL
    Updating git-repo `https://github.com/MaximeBouton/AutomotiveSafeRL`
ERROR: expected the file `src/AutomotiveSafeRL.jl` to exist for package `AutomotiveSafeRL` at `F:\C_TEMP\user_temp\jl_QLzXut`     
Then i delete `AutomotiveSafeRL at `F:\C_TEMP\user_temp\jl_QLzXut`   .
But it does not work!

(@v1.6) pkg> add https://github.com/MaximeBouton/AutomotiveSafeRL
    Updating git-repo `https://github.com/MaximeBouton/AutomotiveSafeRL`
ERROR: expected the file `src/AutomotiveSafeRL.jl` to exist for package `AutomotiveSafeRL` at `F:\C_TEMP\user_temp\jl_PVMB7g`

**Comment by MaximeBouton** [comment]
Sorry if this is a bit confusing but this repo is *not* a julia package and cannot be installed with add. Cloning the repository and installing the dependencies should be enough to run the code.

**Comment by tingtingLiuLiu** [comment]
Thanks
